unstable_features = true
newline_style = "Unix"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
ignore = ["src/bindings/operator_manager.rs", "src/bindings/ledger.rs", "src/bindings/vault.rs", "src/bindings/mock_token.rs"]
