[package]
name = "zkvm-fib"
version = "0.1.0"
edition = "2021"

[dependencies]
fib-methods = { path = "methods" }
risc0-zkvm = "0.19.1"
clap = { version = "4.4.11", features = ["derive"] }

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
metal = ["risc0-zkvm/metal"]
prove = ["risc0-zkvm/prove"]
